"""Initial migration

Revision ID: 30737cbd92e9
Revises: 
Create Date: 2025-08-29 01:06:50.556022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30737cbd92e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mpesa_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('shortcode', sa.String(length=255), nullable=False),
    sa.Column('encrypted_consumer_key', sa.LargeBinary(), nullable=False),
    sa.Column('encrypted_consumer_secret', sa.LargeBinary(), nullable=False),
    sa.Column('encrypted_passkey', sa.LargeBinary(), nullable=False),
    sa.Column('is_registered', sa.Boolean(), nullable=True),
    sa.Column('registration_response', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('mpesa_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('mpesa_trans_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transaction_time', sa.String(length=255), nullable=False),
    sa.Column('account_reference', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mpesa_trans_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mpesa_transactions')
    op.drop_table('mpesa_integrations')
    # ### end Alembic commands ###
